### ISSUE TITLE
Duplicate example

### ISSUE THREAD

**Issue by Infinity4B** [purepisces/Wenqing-Machine_Learning_Blog#1]
https://github.com/purepisces/Wenqing-Machine_Learning_Blog/blob/ba4bcf6fe7fafc3aaf67f319d645039ae3781159/Foundational-Concepts-in-Machine-Learning/Linear-Algebra/Numpy-Tips.md?plain=1#L708
In the Detailed Broadcasting Rules section, the "Can't Broadcasting" example is exactly the same as the example above?

**Comment by purepisces** [comment]
Yes, Thank you so much for pointing that out! I've modified it to a new version. You can check my progress.txt, which contains all the markdown files that I've already finished. I haven't thoroughly checked the other markdown files yet; I've just added content to them for now.

**Example2: Can't Broadcasting**
```python
import numpy as np
c = np.array([1, 2, 3])
print(c.shape) #(3,)
new_shape = (3,2)
print(np.broadcast_to(c, new_shape))
```
1.  **Original Shape**: `(3,)`
    
    -   This shape has only one dimension: `3`. For broadcasting purposes, it can be treated as `(1, 3)`.
2.  **Target Shape**: `(3, 2)`

**Comparison**

-   **Trailing Dimensions**: `3` (original) vs. `2` (target) – these are not compatible because they are not equal and neither is 1.
-   **Leading Dimensions**: `1` (original) vs. `3` (target) – these are compatible because 1 can be expanded to 3.

Since the trailing dimensions do not match and are not compatible, broadcasting cannot proceed.

**Comment by purepisces** [comment]
BTW, thank you so much for taking the time to carefully read my machine learning blog. I'm thrilled to know that people are engaging with it. I'll continue to improve it, and if you have any other questions, I'm always happy to discuss them!

**Comment by purepisces** [comment]
> https://github.com/purepisces/Wenqing-Machine_Learning_Blog/blob/ba4bcf6fe7fafc3aaf67f319d645039ae3781159/Foundational-Concepts-in-Machine-Learning/Linear-Algebra/Numpy-Tips.md?plain=1#L708
> 
> 
> In the Detailed Broadcasting Rules section, the "Can't Broadcasting" example is exactly the same as the example above?

Thank you so much for taking the time to carefully read my machine learning blog. I'm thrilled to know that people are engaging with it. I'll continue to improve it, and if you have any other questions, I'm always happy to discuss them!

> https://github.com/purepisces/Wenqing-Machine_Learning_Blog/blob/ba4bcf6fe7fafc3aaf67f319d645039ae3781159/Foundational-Concepts-in-Machine-Learning/Linear-Algebra/Numpy-Tips.md?plain=1#L708
> 
> 
> In the Detailed Broadcasting Rules section, the "Can't Broadcasting" example is exactly the same as the example above?

Yes, Thank you so much for pointing that out! I've modified it to a new version. You can check my progress.txt, which contains all the markdown files that I've already finished. I haven't thoroughly checked the other markdown files yet; I've just added content to them for now.

**Example2: Can't Broadcasting**
```python
import numpy as np
c = np.array([1, 2, 3])
print(c.shape) #(3,)
new_shape = (3,2)
print(np.broadcast_to(c, new_shape))
```
1.  **Original Shape**: `(3,)`
    
    -   This shape has only one dimension: `3`. For broadcasting purposes, it can be treated as `(1, 3)`.
2.  **Target Shape**: `(3, 2)`

**Comparison**

-   **Trailing Dimensions**: `3` (original) vs. `2` (target) – these are not compatible because they are not equal and neither is 1.
-   **Leading Dimensions**: `1` (original) vs. `3` (target) – these are compatible because 1 can be expanded to 3.

Since the trailing dimensions do not match and are not compatible, broadcasting cannot proceed.

**Comment by purepisces** [comment]
> https://github.com/purepisces/Wenqing-Machine_Learning_Blog/blob/ba4bcf6fe7fafc3aaf67f319d645039ae3781159/Foundational-Concepts-in-Machine-Learning/Linear-Algebra/Numpy-Tips.md?plain=1#L708
> 
> 
> In the Detailed Broadcasting Rules section, the "Can't Broadcasting" example is exactly the same as the example above?

By the way, thank you so much for taking the time to carefully read my machine learning blog. I'm thrilled to know that people are engaging with it. I'll continue to improve it, and if you have any other questions, I'm always happy to discuss them! :D

**Comment by Infinity4B** [comment]
Seems like the update of this part has not been uploaded it?

BTW, I have found another promblem in https://github.com/purepisces/Wenqing-Machine_Learning_Blog/blob/ba4bcf6fe7fafc3aaf67f319d645039ae3781159/Deep-Learning-Concepts/Basic-Neural-Network-Concepts/Activation-Functions/activation-functions.md?plain=1#L3, which is mainly due to relative path.

**Comment by purepisces** [comment]
> Seems like the update of this part has not been uploaded it?
> 
> BTW, I have found another promblem in
> 
> https://github.com/purepisces/Wenqing-Machine_Learning_Blog/blob/ba4bcf6fe7fafc3aaf67f319d645039ae3781159/Deep-Learning-Concepts/Basic-Neural-Network-Concepts/Activation-Functions/activation-functions.md?plain=1#L3
> 
> , which is mainly due to relative path.

I have uploaded the new markdown 12 hours ago, could you check again? 
Yes, I have updated the relative path, thank you! :D

**Comment by Infinity4B** [comment]
You're welcome. Thank you for your excellent work! I'll open a new issue if I have other problems.

**Comment by purepisces** [comment]
> You're welcome. Thank you for your excellent work! I'll open a new issue if I have other problems.

Yes, that'll be great! :D I'm looking forward to it! 😊
